version: '3.7'
services:

  server:
    container_name: server-http
    build: ./Server
    depends_on:
    - grpc_server
    - redis
    - redis2
    - redis3
    ports:
      - "3000:3000"
    
  grpc_server:
    container_name: server-grpc
    build: ./gRPC
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: docker.io/bitnami/postgresql:14
    volumes:
      - ./Database/db/:/docker-entrypoint-initdb.d/test-init.sql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_DATABASE=dataset
    ports:
      - "5432:5432"

  redis:
    container_name: redis_1_master
    image: bitnami/redis:7.0.4
    restart: always
    ports:
      - "7000:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 2mb --maxmemory-policy allkeys-lfu
  
  redis2:
    image: bitnami/redis:7.0.4
    container_name: redis_2
    ports:
      - "7001:6379"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_PORT_NUMBER=6379
    restart: always

  redis3:
    image: bitnami/redis:7.0.4
    container_name: redis_3
    ports:
      - "7002:6379"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_PORT_NUMBER=6379
    restart: always

  